name: RPGLoot
version: '1.0.0'
main: com.ricardo.rpgloot.RPGLootPlugin
api-version: '1.21'
author: Ricardo
description: RPG rarity system for weapons with randomized mob drops (Common to Legendary)

commands:
  rpgloot:
    description: RPGLoot test commands
    usage: /rpgloot <get|getall> [rarity] [material]
    permission: rpgloot.admin
